<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxkxtaA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxkxtaA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxkxtaA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxkxtaA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxkxtaA\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxkxtaA',
    'container.build_id' => '8154e39d',
    'container.build_time' => 1707339260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxkxtaA');
