#index:
#    path: /
#    controller: App\Controller\DefaultController::index
export_candidature_pdf:
    path: '/candidature/export/pdf/{id}'
    controller: 'App\Controller\CandidatureController::exportPdf'
