#index:
#    path: /
#    controller: App\Controller\DefaultController::index
export_candidature_pdf:
    path: '/candidature/{id}/export/pdf'
    controller: App\Controller\CandidatureController\exportCandidaturePdf